import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="pl">
        <body className={`${inter.className} antialiased`}>
          <header className="container mx-auto flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <Button variant="outline" asChild>
                <SignInButton />
              </Button>
              <Button asChild>
                <SignUpButton />
              </Button>
            </SignedOut>
            <SignedIn>
              <Link href="/learn">
                <Button variant="outline">Nauka</Button>
              </Link>
              <Link href="/solve">
                <Button variant="outline">Rozwiąż zadanie</Button>
              </Link>
              <Link href="/stats">
                <Button variant="outline">Statystyki</Button>
              </Link>
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
